import type { User, School, Course, CourseCategory, DashboardStats, Class, Enrollment } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@eduvaza.com',
    name: 'Super Admin',
    role: 'super_admin',
    createdAt: new Date('2024-01-01'),
    isActive: true,
  },
  {
    id: 'school-1',
    email: 'school@greenvalley.edu',
    name: 'Green Valley School',
    role: 'school',
    schoolId: 'sch-1',
    createdAt: new Date('2024-01-15'),
    isActive: true,
  },
  {
    id: 'teacher-1',
    email: 'teacher@eduvaza.com',
    name: 'John Mwamba',
    role: 'teacher',
    schoolId: 'sch-1',
    createdAt: new Date('2024-02-01'),
    isActive: true,
  },
  {
    id: 'student-1',
    email: 'student@eduvaza.com',
    name: 'Amara Diallo',
    role: 'student',
    schoolId: 'sch-1',
    createdAt: new Date('2024-03-01'),
    isActive: true,
  },
];

export const mockSchools: School[] = [
  {
    id: 'sch-1',
    name: 'Green Valley International School',
    email: 'info@greenvalley.edu',
    phone: '+254 700 123456',
    address: 'Nairobi, Kenya',
    status: 'approved',
    teacherCount: 45,
    studentCount: 850,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'sch-2',
    name: 'Lagos Academy of Excellence',
    email: 'info@lagosacademy.ng',
    phone: '+234 800 987654',
    address: 'Lagos, Nigeria',
    status: 'approved',
    teacherCount: 62,
    studentCount: 1200,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'sch-3',
    name: 'Cape Town Learning Center',
    email: 'info@ctlc.za',
    phone: '+27 21 555 1234',
    address: 'Cape Town, South Africa',
    status: 'pending',
    teacherCount: 28,
    studentCount: 540,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'sch-4',
    name: 'Accra International School',
    email: 'info@accra-intl.gh',
    phone: '+233 30 254 7890',
    address: 'Accra, Ghana',
    status: 'pending',
    teacherCount: 35,
    studentCount: 680,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'sch-5',
    name: 'Dar es Salaam Academy',
    email: 'info@dsacademy.tz',
    phone: '+255 22 266 1234',
    address: 'Dar es Salaam, Tanzania',
    status: 'suspended',
    teacherCount: 20,
    studentCount: 380,
    createdAt: new Date('2024-01-05'),
  },
];

export const mockCategories: CourseCategory[] = [
  { id: 'cat-1', name: 'Mathematics', icon: '📐', color: '#FF6B35', courseCount: 45 },
  { id: 'cat-2', name: 'Science', icon: '🔬', color: '#6B35FF', courseCount: 38 },
  { id: 'cat-3', name: 'Languages', icon: '📚', color: '#35B5FF', courseCount: 52 },
  { id: 'cat-4', name: 'Technology', icon: '💻', color: '#35FF6B', courseCount: 29 },
  { id: 'cat-5', name: 'Arts & Design', icon: '🎨', color: '#FF35B5', courseCount: 24 },
  { id: 'cat-6', name: 'Business', icon: '📊', color: '#FFB535', courseCount: 31 },
];

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Introduction to Algebra',
    description: 'Master the fundamentals of algebra with practical examples and exercises designed for African learners.',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
    teacherId: 'teacher-1',
    teacherName: 'John Mwamba',
    schoolId: 'sch-1',
    language: 'en',
    category: 'Mathematics',
    curriculum: 'Cambridge IGCSE',
    level: 'beginner',
    lessons: [
      { id: 'l1', courseId: 'course-1', title: 'What is Algebra?', content: '<h2>Introduction to Algebra</h2><p>Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols. In elementary algebra, those symbols represent quantities without fixed values, known as variables.</p><p>The purpose of algebra is to make it easy to state a mathematical relationship and its equation by using letters of the alphabet or other symbols to represent entities as a form of shorthand.</p>', contentType: 'text', order: 1, duration: 15 },
      { id: 'l2', courseId: 'course-1', title: 'Variables and Constants', content: '', contentType: 'pdf', pdfUrl: 'https://www.africau.edu/images/default/sample.pdf', order: 2, duration: 20 },
      { id: 'l3', courseId: 'course-1', title: 'Simple Equations Video', content: 'Learn to solve simple algebraic equations step by step.', contentType: 'video', videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', order: 3, duration: 25 },
    ],
    enrolledCount: 234,
    isPublished: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'course-2',
    title: 'Basic Science: Our Environment',
    description: 'Explore the natural world around us with engaging content about ecosystems, weather, and conservation.',
    thumbnail: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400',
    teacherId: 'teacher-2',
    teacherName: 'Fatima Osei',
    schoolId: 'sch-2',
    language: 'en',
    category: 'Science',
    curriculum: 'African Curriculum',
    level: 'beginner',
    lessons: [
      { id: 'l4', courseId: 'course-2', title: 'Understanding Ecosystems', content: '', contentType: 'video', videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', order: 1, duration: 20 },
      { id: 'l5', courseId: 'course-2', title: 'Weather and Climate', content: '', contentType: 'pdf', pdfUrl: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/img/table-word.pdf', order: 2, duration: 25 },
    ],
    enrolledCount: 456,
    isPublished: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'course-3',
    title: 'French for Beginners',
    description: 'Start your French language journey with this comprehensive course designed for African French learners.',
    thumbnail: 'https://images.unsplash.com/photo-1549737221-bef65e2604a6?w=400',
    teacherId: 'teacher-3',
    teacherName: 'Marie Kouassi',
    language: 'fr',
    category: 'Languages',
    level: 'beginner',
    lessons: [
      { id: 'l6', courseId: 'course-3', title: 'Bonjour! Introductions', content: 'Learning to greet and introduce yourself...', contentType: 'text', order: 1, duration: 15 },
      { id: 'l7', courseId: 'course-3', title: 'Numbers and Counting', content: 'Les nombres de 1 à 100...', contentType: 'text', order: 2, duration: 20 },
    ],
    enrolledCount: 312,
    isPublished: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'course-4',
    title: 'Web Development Basics',
    description: 'Learn to build websites from scratch with HTML, CSS, and JavaScript. Perfect for beginners.',
    thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400',
    teacherId: 'teacher-1',
    teacherName: 'John Mwamba',
    language: 'en',
    category: 'Technology',
    level: 'beginner',
    lessons: [
      { id: 'l8', courseId: 'course-4', title: 'Introduction to HTML', content: 'Building the structure of web pages...', contentType: 'text', order: 1, duration: 30 },
      { id: 'l9', courseId: 'course-4', title: 'Styling with CSS', content: 'Making your pages beautiful...', contentType: 'text', order: 2, duration: 35 },
    ],
    enrolledCount: 189,
    isPublished: true,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'course-5',
    title: 'African Art History',
    description: 'Discover the rich artistic heritage of Africa from ancient times to contemporary movements.',
    thumbnail: 'https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=400',
    teacherId: 'teacher-4',
    teacherName: 'Kwame Asante',
    language: 'en',
    category: 'Arts & Design',
    level: 'intermediate',
    lessons: [
      { id: 'l10', courseId: 'course-5', title: 'Ancient African Art', content: 'Exploring prehistoric and ancient artwork...', contentType: 'text', order: 1, duration: 25 },
    ],
    enrolledCount: 98,
    isPublished: true,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'course-6',
    title: 'Introduction to Swahili',
    description: 'Learn the beautiful Swahili language spoken across East Africa. Karibu sana!',
    thumbnail: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400',
    teacherId: 'teacher-5',
    teacherName: 'Juma Mwinyi',
    language: 'sw',
    category: 'Languages',
    level: 'beginner',
    lessons: [
      { id: 'l11', courseId: 'course-6', title: 'Habari! Greetings', content: 'Common Swahili greetings and responses...', contentType: 'text', order: 1, duration: 15 },
    ],
    enrolledCount: 276,
    isPublished: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-03-12'),
  },
];

export const mockClasses: Class[] = [
  { id: 'class-1', schoolId: 'sch-1', name: 'Grade 8A', grade: '8', teacherId: 'teacher-1', studentCount: 35, assignedCourses: ['course-1', 'course-2'] },
  { id: 'class-2', schoolId: 'sch-1', name: 'Grade 8B', grade: '8', teacherId: 'teacher-2', studentCount: 32, assignedCourses: ['course-1'] },
  { id: 'class-3', schoolId: 'sch-1', name: 'Grade 9A', grade: '9', studentCount: 38, assignedCourses: ['course-4'] },
];

export const mockEnrollments: Enrollment[] = [
  { id: 'enr-1', studentId: 'student-1', courseId: 'course-1', progress: 65, completedLessons: ['l1', 'l2'], lastAccessedAt: new Date(), enrolledAt: new Date('2024-03-01') },
  { id: 'enr-2', studentId: 'student-1', courseId: 'course-4', progress: 30, completedLessons: ['l8'], lastAccessedAt: new Date(), enrolledAt: new Date('2024-03-10') },
];

export const mockStats: DashboardStats = {
  totalSchools: 156,
  totalTeachers: 2340,
  totalStudents: 45680,
  totalCourses: 892,
  activeUsers: 12450,
  pendingApprovals: 24,
};
