import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, 
  AlertTriangle, 
  Check, 
  X, 
  Loader2, 
  Eye,
  FileText,
  Wand2
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import type { AIDraft, Quiz } from '@/types/quiz';

interface AIDraftGeneratorProps {
  type: 'quiz' | 'lesson_summary';
  onGenerate: (content: string) => Promise<AIDraft>;
  onApprove: (draft: AIDraft) => void;
  onReject: (draft: AIDraft) => void;
}

export const AIDraftGenerator = ({ 
  type, 
  onGenerate, 
  onApprove, 
  onReject 
}: AIDraftGeneratorProps) => {
  const [sourceContent, setSourceContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [draft, setDraft] = useState<AIDraft | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  const handleGenerate = async () => {
    if (!sourceContent.trim()) return;
    setIsGenerating(true);
    try {
      const newDraft = await onGenerate(sourceContent);
      setDraft(newDraft);
      setShowPreview(true);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleApprove = () => {
    if (draft) {
      onApprove(draft);
      setDraft(null);
      setShowPreview(false);
      setSourceContent('');
    }
  };

  const handleReject = () => {
    if (draft) {
      onReject(draft);
      setDraft(null);
      setShowPreview(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Warning Banner */}
      <Alert className="border-warning/50 bg-warning/5">
        <AlertTriangle className="h-4 w-4 text-warning" />
        <AlertTitle className="text-warning">AI-Generated Content</AlertTitle>
        <AlertDescription className="text-muted-foreground">
          This content is generated by AI and requires your review and approval before use. 
          Always verify accuracy and appropriateness for your students.
        </AlertDescription>
      </Alert>

      {/* Generator Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-warning" />
            {type === 'quiz' ? 'Generate Quiz Draft' : 'Generate Lesson Summary'}
            <Badge variant="secondary" className="ml-auto">
              Draft Only
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">
              {type === 'quiz' 
                ? 'Enter lesson content or topic to generate quiz questions:' 
                : 'Enter lesson content to summarize:'}
            </label>
            <Textarea
              value={sourceContent}
              onChange={(e) => setSourceContent(e.target.value)}
              placeholder={
                type === 'quiz'
                  ? 'e.g., This lesson covers algebraic expressions, including variables, constants, and coefficients...'
                  : 'Paste your lesson content here...'
              }
              rows={6}
              disabled={isGenerating}
            />
          </div>

          <Button 
            onClick={handleGenerate} 
            disabled={!sourceContent.trim() || isGenerating}
            className="w-full"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Wand2 className="h-4 w-4 mr-2" />
                Generate {type === 'quiz' ? 'Quiz' : 'Summary'}
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Preview Modal */}
      <AnimatePresence>
        {showPreview && draft && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-foreground/20 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              className="bg-card rounded-xl shadow-xl max-w-2xl w-full max-h-[80vh] overflow-hidden"
            >
              <div className="p-4 border-b flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Sparkles className="h-5 w-5 text-warning" />
                  <h3 className="font-semibold">AI-Generated Draft</h3>
                  <Badge variant="outline" className="border-warning text-warning">
                    Requires Approval
                  </Badge>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setShowPreview(false)}>
                  <X className="h-4 w-4" />
                </Button>
              </div>

              <div className="p-4 overflow-y-auto max-h-[50vh]">
                {type === 'quiz' && typeof draft.generatedContent === 'object' && (
                  <div className="space-y-4">
                    <div className="p-3 rounded-lg bg-muted">
                      <h4 className="font-semibold">{(draft.generatedContent as Quiz).title}</h4>
                      <p className="text-sm text-muted-foreground">{(draft.generatedContent as Quiz).description}</p>
                      <div className="flex gap-2 mt-2">
                        <Badge>{(draft.generatedContent as Quiz).questions.length} questions</Badge>
                        <Badge variant="outline">{(draft.generatedContent as Quiz).totalPoints} points</Badge>
                      </div>
                    </div>
                    
                    {(draft.generatedContent as Quiz).questions.map((q, i) => (
                      <div key={q.id} className="p-3 rounded-lg border">
                        <div className="flex items-start gap-2">
                          <span className="flex items-center justify-center w-6 h-6 rounded-full bg-primary text-primary-foreground text-sm font-medium">
                            {i + 1}
                          </span>
                          <div className="flex-1">
                            <p className="font-medium">{q.question}</p>
                            {q.options && (
                              <div className="mt-2 space-y-1">
                                {q.options.map((opt, oi) => (
                                  <div 
                                    key={opt.id} 
                                    className={`p-2 rounded text-sm ${opt.isCorrect ? 'bg-success/10 text-success' : ''}`}
                                  >
                                    {String.fromCharCode(65 + oi)}. {opt.text}
                                    {opt.isCorrect && <Check className="inline h-4 w-4 ml-2" />}
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}

                {type === 'lesson_summary' && typeof draft.generatedContent === 'string' && (
                  <div className="prose prose-sm max-w-none">
                    <div className="p-4 rounded-lg bg-muted">
                      <FileText className="h-5 w-5 mb-2 text-primary" />
                      <p>{draft.generatedContent}</p>
                    </div>
                  </div>
                )}
              </div>

              <div className="p-4 border-t bg-muted/30">
                <Alert className="mb-4 border-warning/50 bg-warning/5">
                  <AlertTriangle className="h-4 w-4 text-warning" />
                  <AlertDescription className="text-sm">
                    Please review this content carefully before approving. AI-generated content may contain inaccuracies.
                  </AlertDescription>
                </Alert>
                
                <div className="flex gap-3">
                  <Button 
                    variant="outline" 
                    className="flex-1 border-destructive text-destructive hover:bg-destructive hover:text-destructive-foreground"
                    onClick={handleReject}
                  >
                    <X className="h-4 w-4 mr-2" />
                    Reject & Edit
                  </Button>
                  <Button className="flex-1" onClick={handleApprove}>
                    <Check className="h-4 w-4 mr-2" />
                    Approve & Use
                  </Button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
